<?php

use Drupal\node\Entity\Node;

function sis_almanac_theme() {
  return [
    'almanac' => [
      'variables' => ['date' => NULL, 'day' => NULL, 'month' => NULL, 'content' => NULL, 'active' => FALSE]
    ],
     'almanacs' => [
      'variables' => ['almanacs' => []]
    ]
  ];
}

function sis_almanac_preprocess_block__inline_block__almanac(&$variables) {
  /** @var \Drupal\sis_almanac\Services\AlmanacContentDeliveryService $almanacContentDeliveryService */
  $almanacContentDeliveryService = \Drupal::service('sis_almanac.content_delivery');
  $variables['almanac'] = $almanacContentDeliveryService->getAlmanac();
}

function sis_almanac_preprocess_page(&$variables) {
  /** @var \Drupal\sis_almanac\Services\AlmanacContentDeliveryService $almanacContentDeliveryService */
  $almanacContentDeliveryService = \Drupal::service('sis_almanac.content_delivery');
  $variables['almanac'] = $almanacContentDeliveryService->getAlmanac();
}
